### ISSUE TITLE
Error on generate Migration

### ISSUE THREAD

**Issue by M2xAy** [VantageSoftware/EFCore.TimeTraveler#3]
Hi
Firstly Thank you for this Project

I receive this error on creating migration, have you any Idea ?
The current CSharpHelper cannot scaffold literals of type 'EFCore.TimeTraveler.TemporalTables'. Configure your services to use one that can.

Thank you
Best regards

**Comment by M2xAy** [comment]
I found the error Thank you

I forget the    options.AddInterceptors(new TimeTravelInterceptor()); under stratup usesql options

**Comment by M2xAy** [comment]
ah Sorry I was wrong, I have still this error any Idea ?

**Comment by bbrandt** [comment]
Hi @M2xAy ,

Thanks for trying out the project.  What version of EF Core are you on?  Do you have a sample project you can upload?  Thanks!

**Comment by M2xAy** [comment]
> Hi @M2xAy ,
> 
> Thanks for trying out the project. What version of EF Core are you on? The library requires EF Core 3.1. Do you have a sample project you can upload? Thanks!


Hi bbrand
Thank you for your answer, i use 3.1.1 i was able to test the package and get history, but i receive still the error on a new migration, I can create test project that I can reproduce the error code, I will do this tomorrow
Best regards

**Comment by M2xAy** [comment]
Hi bbrandt
I cleaned the solution and updated my .net core and nugets, now I do not receive the error

Best regards

**Comment by bbrandt** [comment]
Thanks for the update @M2xAy
