### ISSUE TITLE
Unable to scaffold

### ISSUE THREAD

**Issue by Adam-Langley** [VantageSoftware/EFCore.TimeTraveler#5]
I'm linked against .net Core and Ef Core 3.1.1, and I get this when adding a migration that includes temporal query:

The current CSharpHelper cannot scaffold literals of type 'EFCore.TimeTraveler.TemporalTables'. Configure your services to use one that can.

I dont see any code in Github which would generate the ALTER TABLE statements, so I'm curious - where is all the code that performs the scaffolding?

**Comment by bbrandt** [comment]
Hi @Adam-Langley, 
Thank you for reporting this issue.  @M2xAy recently reported a similar issue in #3, but @M2xAy resolved it locally before I was able to reproduce it.  Are you able to provide a small sample project that reproduces the issue?

EFCore.TimeTraveler does not have any functionality for EF Core Migrations.  I use Fluent Migrations currently, so do not have much experience with EF Core Migrations.  In my test project, [I used SQL](https://github.com/VantageSoftware/EFCore.TimeTraveler/blob/8f8b3e21249e58da2277fb51b74a697eef55e57d/tests/EFCore.TimeTravelerTests/Migrations/20191209231909_Initialize.cs#L46) to convert the tables to System-Versioned Temporal Tables.


For better migration support, [EntityFrameworkCore.TemporalTables](https://github.com/findulov/EntityFrameworkCore.TemporalTables) looks quite promising.

**Comment by bbrandt** [comment]
Ah, I see you already found [EntityFrameworkCore.TemporalTables](https://github.com/findulov/EntityFrameworkCore.TemporalTables).  Let me know if your experience is good and I will add a link to the project from the EFCore.TimeTraveler readme.md.

https://github.com/findulov/EntityFrameworkCore.TemporalTables/issues/12

**Comment by Adam-Langley** [comment]
Hi @bbrandt, thank you, yes I found that package which got me up and running.
The last piece of the puzzle for me was then the querying capability - however I really needed joined entities to honour a consistent point-in-time.

I see you're using the interceptor approach - meaning you lose all access to the AST. 
EF Core is much more extensible than it used to be, so I've thrown together an implementation that uses the underlying visitor pipeline. Does what I need.
Shame about the lack of documentation on the EF core internal API - so it took a massive learning curve, but once I figured it out - I'm stunned with how little code was required.

https://github.com/Adam-Langley/efcore-temporal-query

**Comment by bbrandt** [comment]
Awesome!  Thanks for open sourcing your project.  Do you think that after your repo has some tests we'd be able to submit it to @ajcvickers as a potential solution to be merged into the EF Core library?

I added a link to your project in my readme here to start redirecting people:
https://github.com/VantageSoftware/EFCore.TimeTraveler#update-352020

**Comment by Adam-Langley** [comment]
Hi - thanks for the attribution.
I'm totally for the code being re-integrated (and yes, tests would be ideal).
I get the feeling that given the simplicity of the code however, I think the roadblock is likely to be the development process, QA and such, rather than the writing of the code itself.
But hey - fingers crossed!
If you're interested in writing some tests, I'm happy to make sure they green-light.
